# _config.yml
title: DBWS 2026
description: 東海関西データベースワークショップ 2026
lang: ja
timezone: Asia/Tokyo

url: "https://dbws2026.github.io"
baseurl: ""

markdown: kramdown
theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

header_pages:
  - index.md
  - program.md
  - attend.md
  - venue.md
  - awards.md

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed